package com.github.cokelee777.a2aclient;

import org.springframework.util.Assert;

/**
 * Represents a chat response sent to the client.
 * <p>
 * This record contains the session ID and the response message generated by the LLM. Both
 * fields are validated to ensure they are not blank.
 * </p>
 *
 * @param sessionId the unique identifier for the conversation session; must not be blank
 * @param response the response message from the LLM; must not be blank
 */
public record ChatResponse(String sessionId, String response) {

	/**
	 * Compact constructor that validates both {@code sessionId} and {@code response} are
	 * not blank.
	 * @param sessionId the session ID; must not be blank
	 * @param response the response message; must not be blank
	 * @throws IllegalArgumentException if sessionId or response is blank
	 */
	public ChatResponse {
		Assert.hasText(sessionId, "sessionId must not be blank");
		Assert.hasText(response, "response must not be blank");
	}
}
